package ni.shikatu.re_extera;

import org.telegram.messenger.LocaleController;

public class Localization {
    public static String ADDITIONAL_SETTINGS;
    public static String ALPHA_WARNING;
    public static String ALWAYS;
    public static String BASED_ON_GLOBAL;
    public static String CANCEL;
    public static String CLEARING_NOW;
    public static String CLEAR_DB;
    public static String CLEAR_DELETED;
    public static String CUSTOM_PREFIX;
    public static String DELETED_AND_EDITED_MESSAGES;
    public static String DISABLE_BLUR;
    public static String ENABLE_ALPHA;
    public static String EXCEPTION_READING_TEXT;
    public static String EXCEPTION_TYPING_TEXT;
    public static String FORWARDED;
    public static String FORWARDED_TO_SAVED_MESSAGES;
    public static String GENERAL;
    public static String GHOST_MODE;
    public static String HIDE_ONLINE_STATUS;
    public static String HIDE_READING_MESSAGE;
    public static String HIDE_TYPING_STATUS;
    public static String HOLD_FOR_ADDITIONAL_SETTINGS;
    public static String INFINITY_STARS;
    public static String LEAVE_BLANK_FOR_RECYCLE;
    public static String MESSAGE_HISTORY;
    public static String MESSAGE_HISTORY_TITLE;
    public static String MESSAGE_HISTORY_TOGGLE;
    public static String NEVER;
    public static String NO;
    public static String NO_FORWARD;
    public static String NO_READ_STORIES;
    public static String OTHER;
    public static String READ;
    public static String RED_DELETED_MARK;
    public static String REMOVE_FLAG_SECURE;
    public static String RE_EXTERA_SETTINGS;
    public static String SAVE_DELETED_MESSAGES;
    public static String SAVE_ONE_TIME_MESSAGES;
    public static String THANKS;
    public static String TYPE;
    public static String USE_SCHEDULE;
    public static String YES;

    public static void updateStrings() {
        String currentLang = LocaleController.getInstance().getCurrentLocale().getLanguage();
        if ("ru".equals(currentLang)) {
            HIDE_READING_MESSAGE = "Не читать сообщения";
            HIDE_TYPING_STATUS = "Не показывать статус \"печатает\"";
            HIDE_ONLINE_STATUS = "Не показывать статус \"онлайн\"";
            NO_READ_STORIES = "Не читать истории";
            ENABLE_ALPHA = "Полупрозрачные удаленки";
            ALPHA_WARNING = "Эта функция кушает очень много";
            GENERAL = "Общие";
            THANKS = "Спасибо @bleizix";
            RE_EXTERA_SETTINGS = "Настройки re:extera";
            SAVE_DELETED_MESSAGES = "Сохранять удаленные сообщения";
            MESSAGE_HISTORY = "История";
            MESSAGE_HISTORY_TOGGLE = "Сохранить историю правок";
            MESSAGE_HISTORY_TITLE = "История правок";
            REMOVE_FLAG_SECURE = "Игнорировать FLAG_SECURE";
            USE_SCHEDULE = "Использовать отложку";
            CLEAR_DB = "Очистить БД";
            YES = "Да";
            NO = "Нет";
            CUSTOM_PREFIX = "Метка удаленок";
            LEAVE_BLANK_FOR_RECYCLE = "Оставьте пустым для иконки 🗑️";
            GHOST_MODE = "Режим призрака";
            DELETED_AND_EDITED_MESSAGES = "Измененные и удаленные сообщения";
            OTHER = "Другое";
            NO_FORWARD = "Убрать ограничения на пересылку";
            RED_DELETED_MARK = "Красная метка удаленок";
            EXCEPTION_READING_TEXT = "Исключение нечиталки";
            EXCEPTION_TYPING_TEXT = "Исключение неписалки";
            BASED_ON_GLOBAL = "В зависимости от глобальных";
            ALWAYS = "Всегда";
            NEVER = "Никогда не";
            READ = "читать";
            TYPE = "писать";
            CLEARING_NOW = "Очистка...";
            CLEAR_DELETED = "Очистить удаленные?";
            FORWARDED_TO_SAVED_MESSAGES = "Переслано в избранное";
            INFINITY_STARS = "Бесконечное количество звезд";
            FORWARDED = "Идет пересылка...";
            CANCEL = "Отмена";
            SAVE_ONE_TIME_MESSAGES = "Сохранять самоуничтожающиеся сообщения";
            DISABLE_BLUR = "Отключить размытие";
            HOLD_FOR_ADDITIONAL_SETTINGS = "Удерживайте для дополнительных настроек";
            ADDITIONAL_SETTINGS = "Дополнительные настройки";
            return;
        }
        HIDE_READING_MESSAGE = "Don't read messages";
        HIDE_TYPING_STATUS = "Don't show \"typing\" status";
        HIDE_ONLINE_STATUS = "Don't show \"online\" status";
        NO_READ_STORIES = "Don't read stories";
        GENERAL = "General";
        THANKS = "Thanks to @bleizix";
        ENABLE_ALPHA = "Half opacity for deleted messages";
        ALPHA_WARNING = "This function eats a lot of cpu";
        RE_EXTERA_SETTINGS = "re:extera Settings";
        SAVE_DELETED_MESSAGES = "Save deleted messages";
        MESSAGE_HISTORY = "History";
        MESSAGE_HISTORY_TOGGLE = "Save message history";
        MESSAGE_HISTORY_TITLE = "Message history";
        REMOVE_FLAG_SECURE = "Ignore FLAG_SECURE";
        USE_SCHEDULE = "Use schedule to send";
        CLEAR_DB = "Clear DB";
        YES = "Yes";
        NO = "No";
        CUSTOM_PREFIX = "Deleted message mark";
        LEAVE_BLANK_FOR_RECYCLE = "Leave blank for 🗑 icon️";
        GHOST_MODE = "Ghost mode";
        DELETED_AND_EDITED_MESSAGES = "Edited and deleted messages";
        OTHER = "Other";
        NO_FORWARD = "Remove forwarding restrictions";
        RED_DELETED_MARK = "Red deleted mark";
        EXCEPTION_READING_TEXT = "Exception reading";
        EXCEPTION_TYPING_TEXT = "Exception typing";
        BASED_ON_GLOBAL = "Based on global";
        ALWAYS = "Always";
        NEVER = "Never";
        READ = "read";
        TYPE = "type";
        CLEARING_NOW = "Clearing...";
        CLEAR_DELETED = "Clear deleted?";
        FORWARDED_TO_SAVED_MESSAGES = "Forwarded to saved messages";
        INFINITY_STARS = "Infinity stars";
        FORWARDED = "Forwarding...";
        CANCEL = "Cancel";
        SAVE_ONE_TIME_MESSAGES = "Save self-destruct messages";
        DISABLE_BLUR = "Disable blur";
        HOLD_FOR_ADDITIONAL_SETTINGS = "Hold for additional settings";
        ADDITIONAL_SETTINGS = "Additional settings";
    }
}
