package ni.shikatu.re_extera.localization;

import org.telegram.messenger.LocaleController;

public class Localization {
    public static String ABOUT_SAVE_SELF_DELETED_MESSAGES;
    public static String ADD;
    public static String ADDITIONAL_SETTINGS;
    public static String ADD_REGEX_FILTER;
    public static String ADD_SETTINGS_TO_DRAWER;
    public static String ADD_TO_SHADOWBAN;
    public static String ALPHA_WARNING;
    public static String ALWAYS;
    public static String BASED_ON_GLOBAL;
    public static String BROKE_HOOKS_DESCRIPTION;
    public static String CANCEL;
    public static String CANT_USE_WITH_PREMIUM;
    public static String CLEARING_NOW;
    public static String CLEAR_DB;
    public static String CLEAR_DELETED;
    public static String CLOSE_APPLICATION;
    public static String CONTINUE_ANYWAY;
    public static String COPIED;
    public static String COPY_FILTER;
    public static String CUSTOM_PREFIX;
    public static String DELETE;
    public static String DELETED_AND_EDITED_MESSAGES;
    public static String DELETED_MESSAGES_TITLE;
    public static String DELETE_FILTER;
    public static String DELETE_FILTER_ABOUT;
    public static String DELETE_FROM_EXCLUSIONS;
    public static String DISABLE_ADS;
    public static String DISABLE_COLORED_REPLIES;
    public static String WORK_IN_BACKGROUND;
    public static String DISABLE_BLUR;
    public static String EDIT_READ;
    public static String EDIT_FILTER;
    public static String EDIT_REGEX_FILTER;
    public static String EDIT_REGEX_PATTERN;
    public static String EDIT_SHADOWBAN;
    public static String EDIT_TYPING;
    public static String ENABLE_ALPHA;
    public static String ENABLE_FILTERS;
    public static String EXCEPTION_READING_TEXT;
    public static String EXCEPTION_TYPING_TEXT;
    public static String EXCLUSIONS;
    public static String FILTERED_MESSAGE;
    public static String FILTERS;
    public static String FILTERS_ABOUT;
    public static String FINALLY_REMOVE_ALL_DELETED_MESSAGES;
    public static String FORWARDED;
    public static String FORWARDED_TO_SAVED_MESSAGES;
    public static String GENERAL;
    public static String GHOST_IN_DRAWER;
    public static String GHOST_MODE;
    public static String GHOST_MODE_DISABLE;
    public static String GHOST_MODE_DISABLED;
    public static String GHOST_MODE_ENABLE;
    public static String GHOST_MODE_ENABLED;
    public static String GHOST_EXCLUDE_GROUPS;
    public static String GHOST_EXCLUDE_CHANNELS;
    public static String GHOST_EXCLUDE_PMS;
    public static String HIDE_DIALOG;
    public static String HIDE_IN_GROUPS;
    public static String HIDE_ONLINE_STATUS;
    public static String HIDE_READING_MESSAGE;
    public static String HIDE_TYPING_STATUS;
    public static String HOLD_FOR_ADDITIONAL_SETTINGS;
    public static String IMMEDIATE_OFFLINE;
    public static String INFINITY_STARS;
    public static String LEAVE_BLANK_FOR_RECYCLE;
    public static String LOCAL_PREMIUM;
    public static String MESSAGE_HISTORY;
    public static String MESSAGE_HISTORY_TITLE;
    public static String MESSAGE_HISTORY_TOGGLE;
    public static String NEVER;
    public static String NO;
    public static String NOT;
    public static String NO_EXLCUSIONS;
    public static String NO_FORWARD;
    public static String NO_FORWARD_ABOUT;
    public static String NO_READ_STORIES;
    public static String NO_SHADOWBANNED;
    public static String OFFLINE;
    public static String ONLY_WITH_GHOST;
    public static String OPEN_CHAT;
    public static String OTHER;
    public static String PATTERN_ERROR;
    public static String READ;
    public static String READ_MESSAGE;
    public static String READ_ON_INTERACT;
    public static String READ_TO;
    public static String RED_DELETED_MARK;
    public static String REMOVE_FLAG_SECURE;
    public static String HIDE_PINNED_MESSAGES;
    public static String DISABLE_CHAT_SWIPE_BACK;
    public static String DISABLE_PROFILE_SWIPE;
    public static String SAVE_PROTECTED_STORIES;
    public static String HIDE_TL_ERROR;
    public static String SHOW_MESSAGE_ID;
    public static String SHOW_ID_IN_MENU;
    public static String ID_COPIED;
    public static String DELETED_MESSAGE;
    public static String MESSAGE_DETAILS;
    public static String SAVE_TO_SAVED_MESSAGES;
    public static String VIEW_ONCE;
    public static String VIEW_ONCE_ABOUT;
    public static String MESSAGE_QUICK_BUTTONS;
    public static String REMOVE_FROM_SHADOWBAN;
    public static String RESTART_APP;
    public static String RESTART_APP_ABOUT;
    public static String RE_EXTERA_SETTINGS;
    public static String SAVE;
    public static String SAVE_ATTACHMENTS;
    public static String SAVE_ATTACHMENTS_SIZE;
    public static String SAVE_ATTACHMENTS_DESC;
    public static String SAVE_BOT_CHATS;
    public static String SAVE_DELETED_MESSAGES;
    public static String SAVE_READ_DATE;
    public static String SAVE_LAST_ONLINE;
    public static String EXPORT_DB;
    public static String IMPORT_DB;
    public static String IMPORT_SUCCESSFUL;
    public static String IMPORT_FAILED;
    public static String EXPORT_SUCCESSFUL;
    public static String EXPORT_FAILED;
    public static String DB_NOT_FOUND;
    public static String READ_AT;
    public static String SAVE_ONE_TIME_MESSAGES;
    public static String SAVE_OWN_MESSAGES;
    public static String SAVE_SELF_DELETED_MESSAGES;
    public static String SEND_SILENCE;
    public static String SHADOWBAN;
    public static String SHADOWBAN_ABOUT;
    public static String SPY;
    public static String CUSTOMIZATION;
    public static String THANKS;
    public static String TYPE;
    public static String TYPE_TO;
    public static String UNKNOWN_DIALOG;
    public static String UNLIMITED;
    public static String UNLOAD_REEXTERA;
    public static String UNLOAD_SUCCESSFULL;
    public static String USE_COLLAPSED_BLOCKQUOTE;
    public static String USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION;
    public static String USE_SCHEDULE;
    public static String VIEW_DELETED;
    public static String WE_BROKE_SOMETHING;
    public static String YES;

    public static void updateStrings() {
        String currentLang = LocaleController.getInstance().getCurrentLocale().getLanguage();
        if ("ru".equals(currentLang)) {
            HIDE_READING_MESSAGE = "Не читать сообщения";
            HIDE_TYPING_STATUS = "Не отправлять \"печатает\"";
            HIDE_ONLINE_STATUS = "Не отправлять \"онлайн\"";
            NO_READ_STORIES = "Не читать истории";
            ENABLE_ALPHA = "Прозрачные удаленные сообщения";
            ALPHA_WARNING = "Эта функция кушает очень много";
            GENERAL = "Общие";
            THANKS = "Спасибо @bleizix";
            RE_EXTERA_SETTINGS = "Настройки re:extera";
            SAVE_DELETED_MESSAGES = "Сохранять удаленные сообщения";
            SAVE_BOT_CHATS = "Сохранять в чатах с ботами";
            SAVE_READ_DATE = "Сохранять дату чтения";
            SAVE_LAST_ONLINE = "Сохранять последний онлайн";
            SAVE_ATTACHMENTS = "Сохранять вложения";
            SAVE_ATTACHMENTS_SIZE = "Максимальный размер папки";
            SAVE_ATTACHMENTS_DESC = "Удаленные медиа будут сохраняться в Downloads/ReExtera/ReExteraAttachments. Старые файлы будут удаляться при превышении лимита.";
            EXPORT_DB = "Экспорт базы данных";
            IMPORT_DB = "Импорт базы данных";
            IMPORT_SUCCESSFUL = "Успешно импортировано! Перезапуск...";
            IMPORT_FAILED = "Ошибка импорта: ";
            EXPORT_SUCCESSFUL = "Экспортировано в Загрузки!";
            EXPORT_FAILED = "Ошибка экспорта: ";
            DB_NOT_FOUND = "База данных не найдена";
            READ_AT = "Прочитано в %s";
            MESSAGE_HISTORY = "История";
            MESSAGE_HISTORY_TOGGLE = "Сохранить историю правок";
            MESSAGE_HISTORY_TITLE = "История правок";
            REMOVE_FLAG_SECURE = "Игнорировать FLAG_SECURE";
            USE_SCHEDULE = "Использовать отложку";
            CLEAR_DB = "Очистить БД";
            YES = "Да";
            NO = "Нет";
            CUSTOM_PREFIX = "Метка удаленок";
            LEAVE_BLANK_FOR_RECYCLE = "Оставьте пустым для иконки 🗑️";
            GHOST_MODE = "Режим призрака";
            UNLIMITED = "Безлимит";
            DELETED_AND_EDITED_MESSAGES = "Измененные и удаленные сообщения";
            OTHER = "Другое";
            NO_FORWARD = "re:forward";
            NO_FORWARD_ABOUT = "re:forward позволяет псевдопересылать сообщения из чатов, где это запрещено";
            RED_DELETED_MARK = "Красная метка удаленок";
            EXCLUSIONS = "Исключения";
            EXCEPTION_READING_TEXT = "Исключение нечиталки";
            EXCEPTION_TYPING_TEXT = "Исключение неписалки";
            GHOST_EXCLUDE_GROUPS = "Не применять для групп";
            GHOST_EXCLUDE_CHANNELS = "Не применять для каналов";
            GHOST_EXCLUDE_PMS = "Не применять для личных сообщений";
            BASED_ON_GLOBAL = "В зависимости от глобальных";
            ALWAYS = "Всегда";
            NEVER = "Никогда";
            NOT = " не ";
            READ = "читать";
            TYPE = "писать";
            READ_TO = "Читать: ";
            TYPE_TO = "Печатать: ";
            DISABLE_ADS = "Отключить рекламу";
            HIDE_PINNED_MESSAGES = "Скрыть закрепленные сообщения";
            DISABLE_CHAT_SWIPE_BACK = "Отключить свайп назад в чате";
            DISABLE_PROFILE_SWIPE = "Отключить свайп в профиле";
            SAVE_PROTECTED_STORIES = "Сохранять защищенные истории";
            HIDE_TL_ERROR = "Скрыть ошибку TL";
            SHOW_MESSAGE_ID = "Показывать ID сообщения";
            SHOW_ID_IN_MENU = "Показывать ID в меню профиля";
            ID_COPIED = "ID скопирован в буфер обмена";
            DELETED_MESSAGE = "Удаленные сообщения";
            MESSAGE_DETAILS = "Детали сообщения";
            SAVE_TO_SAVED_MESSAGES = "Сохранить в Избранное";
            VIEW_ONCE = "Сохранять одноразовые медиа";
            VIEW_ONCE_ABOUT = "Одноразовые фото и видео не будут самоуничтожаться после просмотра.";
            MESSAGE_QUICK_BUTTONS = "Быстрые кнопки на сообщениях";
            DISABLE_COLORED_REPLIES = "Отключить цветные ответы";
            WORK_IN_BACKGROUND = "Работать в фоне";
            CLEARING_NOW = "Очистка...";
            CLEAR_DELETED = "Очистить удаленные";
            FORWARDED_TO_SAVED_MESSAGES = "Переслано в избранное";
            INFINITY_STARS = "Бесконечное количество звезд";
            FORWARDED = "Идет пересылка...";
            CANCEL = "Отмена";
            SAVE_ONE_TIME_MESSAGES = "Сохранять самоуничтожающиеся сообщения";
            DISABLE_BLUR = "Отключить размытие";
            HOLD_FOR_ADDITIONAL_SETTINGS = "Удерживайте для дополнительных настроек";
            ADDITIONAL_SETTINGS = "Дополнительные настройки";
            IMMEDIATE_OFFLINE = "Немедленный оффлайн";
            SAVE_OWN_MESSAGES = "Сохранять свои сообщения";
            SAVE_SELF_DELETED_MESSAGES = "Сохранять сообщения удаленные вручную";
            ABOUT_SAVE_SELF_DELETED_MESSAGES = "Сохраняет сообщения, которые вы самостоятельно удалили через меню \"Удалить\"";
            OFFLINE = "оффлайн?";
            USE_COLLAPSED_BLOCKQUOTE = "Использовать свернутую цитату";
            USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION = "Использовать свернутую цитату для ответа на удаленные сообщения";
            OPEN_CHAT = "Открыть чат";
            EDIT_TYPING = "Изменить исключение неписалки";
            EDIT_READ = "Изменить исключение нечиталки";
            EDIT_FILTER = "Изменить исключение фильтров";
            DELETE_FROM_EXCLUSIONS = "Удалить из исключений";
            UNKNOWN_DIALOG = "Неизвестный диалог";
            NO_EXLCUSIONS = "Нет исключений";
            FILTERS = "Фильтры";
            ADD = "Добавить";
            SAVE = "Сохранить";
            EDIT_REGEX_PATTERN = "Фильтр";
            EDIT_REGEX_FILTER = "Изменить фильтр";
            ADD_REGEX_FILTER = "Добавить фильтр";
            PATTERN_ERROR = "Ошибка шаблона";
            DELETE_FILTER = "Удалить фильтр";
            DELETE_FILTER_ABOUT = "Удалить фильтр?";
            ENABLE_FILTERS = "Включить фильтры";
            FILTERS_ABOUT = "Фильтры позволяют скрывать сообщения, подходящие под regex паттерн.\nИспользуйте regex101.com для составления фильтров.";
            COPY_FILTER = "Копировать фильтр";
            COPIED = "Скопировано";
            READ_MESSAGE = "Прочитать";
            FINALLY_REMOVE_ALL_DELETED_MESSAGES = "Окончательно далить все удаленные сообщения?";
            DELETE = "Удалить";
            VIEW_DELETED = "Посмотреть удаленки";
            GHOST_MODE_ENABLED = "Режим призрака включен";
            GHOST_MODE_DISABLED = "Режим призрака выключен";
            GHOST_IN_DRAWER = "Кнопка призрака в боковом меню";
            SPY = "Шпион";
            CUSTOMIZATION = "Кастомизация";
            GHOST_MODE_ENABLE = "Включить призрака";
            GHOST_MODE_DISABLE = "Выключить призрака";
            ADD_SETTINGS_TO_DRAWER = "Настройки в боковом меню";
            LOCAL_PREMIUM = "Локальный премиум";
            CANT_USE_WITH_PREMIUM = "Нельзя использовать с премиум аккаунтом";
            RESTART_APP = "Перезапустить приложение";
            RESTART_APP_ABOUT = "Это решает 99% всех проблем";
            SEND_SILENCE = "Отправлять без звука";
            ONLY_WITH_GHOST = "Только с призраком";
            DELETED_MESSAGES_TITLE = "Удаленные сообщения";
            UNLOAD_REEXTERA = "Выгрузить хуки re:extera";
            UNLOAD_SUCCESSFULL = "Выгружено успешно";
            WE_BROKE_SOMETHING = "Мы что-то сломали...";
            BROKE_HOOKS_DESCRIPTION = "Приложение не смогло инициализировать необходимые хуки. re:extera не будет работать\n\nЗакрыть приложение или продолжить?";
            CLOSE_APPLICATION = "Закрыть приложение";
            CONTINUE_ANYWAY = "Все равно продолжить";
            READ_ON_INTERACT = "Читать при действиях";
            SHADOWBAN = "Теневой бан";
            ADD_TO_SHADOWBAN = "Добавить в теневой бан";
            REMOVE_FROM_SHADOWBAN = "Убрать из теневого бана";
            EDIT_SHADOWBAN = "Редактировать";
            NO_SHADOWBANNED = "Список пуст";
            HIDE_DIALOG = "Скрыть диалог";
            HIDE_IN_GROUPS = "Скрыть в группах";
            SHADOWBAN_ABOUT = "Теневой бан позволяет скрыть диалог пользователя и/или его сообщения в группах";
            FILTERED_MESSAGE = "Отфильтровано";
            return;
        } else if ("uk".equals(currentLang)) {
            HIDE_READING_MESSAGE = "Не читати повідомлення";
            HIDE_TYPING_STATUS = "Не надсилати \"друкує\"";
            HIDE_ONLINE_STATUS = "Не надсилати \"онлайн\"";
            NO_READ_STORIES = "Не читати історії";
            ENABLE_ALPHA = "Прозорі видалені повідомлення";
            ALPHA_WARNING = "Ця функція використовує дуже багато ресурсів";
            GENERAL = "Загальні";
            THANKS = "Дякуємо @bleizix";
            RE_EXTERA_SETTINGS = "Налаштування re:extera";
            SAVE_DELETED_MESSAGES = "Зберігати видалені повідомлення";
            SAVE_BOT_CHATS = "Зберігати в чатах з ботами";
            SAVE_READ_DATE = "Зберігати дату прочитання";
            SAVE_LAST_ONLINE = "Зберігати останній онлайн";
            SAVE_ATTACHMENTS = "Зберігати вкладення";
            SAVE_ATTACHMENTS_SIZE = "Максимальний розмір папки";
            SAVE_ATTACHMENTS_DESC = "Видалені медіа будуть зберігатися в Downloads/ReExtera/ReExteraAttachments. Старі файли видалятимуться при перевищенні ліміту.";
            EXPORT_DB = "Експорт бази даних";
            IMPORT_DB = "Імпорт бази даних";
            IMPORT_SUCCESSFUL = "Успішно імпортовано! Перезапуск...";
            IMPORT_FAILED = "Помилка імпорту: ";
            EXPORT_SUCCESSFUL = "Експортовано в Завантаження!";
            EXPORT_FAILED = "Помилка експорту: ";
            DB_NOT_FOUND = "Базу даних не знайдено";
            READ_AT = "Прочитано о %s";
            MESSAGE_HISTORY = "Історія";
            MESSAGE_HISTORY_TOGGLE = "Зберегти історію редагувань";
            MESSAGE_HISTORY_TITLE = "Історія редагувань";
            REMOVE_FLAG_SECURE = "Ігнорувати FLAG_SECURE";
            USE_SCHEDULE = "Використовувати відкладене надсилання";
            CLEAR_DB = "Очистити БД";
            YES = "Так";
            NO = "Ні";
            CUSTOM_PREFIX = "Позначка видалених";
            LEAVE_BLANK_FOR_RECYCLE = "Залиште порожнім для іконки 🗑️";
            GHOST_MODE = "Режим привида";
            UNLIMITED = "Безліміт";
            DELETED_AND_EDITED_MESSAGES = "Змінені та видалені повідомлення";
            OTHER = "Інше";
            NO_FORWARD = "re:forward";
            NO_FORWARD_ABOUT = "re:forward дозволяє псевдопересилати повідомлення з чатів, де це заборонено";
            RED_DELETED_MARK = "Червона позначка видалених";
            EXCLUSIONS = "Винятки";
            EXCEPTION_READING_TEXT = "Виняток нечиталки";
            EXCEPTION_TYPING_TEXT = "Виняток неписалки";
            GHOST_EXCLUDE_GROUPS = "Не застосовувати для груп";
            GHOST_EXCLUDE_CHANNELS = "Не застосовувати для каналів";
            GHOST_EXCLUDE_PMS = "Не застосовувати для особистих повідомлень";
            BASED_ON_GLOBAL = "Залежно від глобальних";
            ALWAYS = "Завжди";
            NEVER = "Ніколи";
            NOT = " не ";
            READ = "читати";
            TYPE = "писати";
            READ_TO = "Читати: ";
            TYPE_TO = "Друкувати: ";
            DISABLE_ADS = "Вимкнути рекламу";
            HIDE_PINNED_MESSAGES = "Приховати закріплені повідомлення";
            DISABLE_CHAT_SWIPE_BACK = "Вимкнути свайп назад у чаті";
            DISABLE_PROFILE_SWIPE = "Вимкнути свайп у профілі";
            SAVE_PROTECTED_STORIES = "Зберігати захищені історії";
            HIDE_TL_ERROR = "Приховати помилку TL";
            SHOW_MESSAGE_ID = "Показувати ID повідомлення";
            SHOW_ID_IN_MENU = "Показувати ID у меню профілю";
            ID_COPIED = "ID скопійовано в буфер обміну";
            DELETED_MESSAGE = "Видалені повідомлення";
            MESSAGE_DETAILS = "Деталі повідомлення";
            SAVE_TO_SAVED_MESSAGES = "Зберегти в Обране";
            VIEW_ONCE = "Зберігати одноразові медіа";
            VIEW_ONCE_ABOUT = "Одноразові фото та відео не самознищуватимуться після перегляду.";
            MESSAGE_QUICK_BUTTONS = "Швидкі кнопки на повідомленнях";
            DISABLE_COLORED_REPLIES = "Вимкнути кольорові відповіді";
            WORK_IN_BACKGROUND = "Працювати у фоні";
            CLEARING_NOW = "Очищення...";
            CLEAR_DELETED = "Очистити видалені";
            FORWARDED_TO_SAVED_MESSAGES = "Переслано в збережені";
            INFINITY_STARS = "Нескінченна кількість зірок";
            FORWARDED = "Йде пересилання...";
            CANCEL = "Скасувати";
            SAVE_ONE_TIME_MESSAGES = "Зберігати самознищувані повідомлення";
            DISABLE_BLUR = "Вимкнути розмиття";
            HOLD_FOR_ADDITIONAL_SETTINGS = "Утримуйте для додаткових налаштувань";
            ADDITIONAL_SETTINGS = "Додаткові налаштування";
            IMMEDIATE_OFFLINE = "Негайний офлайн";
            SAVE_OWN_MESSAGES = "Зберігати свої повідомлення";
            SAVE_SELF_DELETED_MESSAGES = "Зберігати повідомлення видалені вручну";
            ABOUT_SAVE_SELF_DELETED_MESSAGES = "Зберігає повідомлення, які ви самостійно видалили через меню \"Видалити\"";
            OFFLINE = "офлайн?";
            USE_COLLAPSED_BLOCKQUOTE = "Використовувати згорнуту цитату";
            USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION = "Використовувати згорнуту цитату для відповіді на видалені повідомлення";
            OPEN_CHAT = "Відкрити чат";
            EDIT_TYPING = "Змінити виняток неписалки";
            EDIT_READ = "Змінити виняток нечиталки";
            EDIT_FILTER = "Змінити виняток фільтрів";
            DELETE_FROM_EXCLUSIONS = "Видалити з винятків";
            UNKNOWN_DIALOG = "Невідомий діалог";
            NO_EXLCUSIONS = "Немає винятків";
            FILTERS = "Фільтри";
            ADD = "Додати";
            SAVE = "Зберегти";
            EDIT_REGEX_PATTERN = "Фільтр";
            EDIT_REGEX_FILTER = "Змінити фільтр";
            ADD_REGEX_FILTER = "Додати фільтр";
            PATTERN_ERROR = "Помилка шаблону";
            DELETE_FILTER = "Видалити фільтр";
            DELETE_FILTER_ABOUT = "Видалити фільтр?";
            ENABLE_FILTERS = "Увімкнути фільтри";
            FILTERS_ABOUT = "Фільтри дозволяють приховувати повідомлення, які відповідають regex шаблону.\nВикористовуйте regex101.com для складання фільтрів.";
            COPY_FILTER = "Копіювати фільтр";
            COPIED = "Скопійовано";
            READ_MESSAGE = "Прочитати";
            FINALLY_REMOVE_ALL_DELETED_MESSAGES = "Остаточно видалити всі видалені повідомлення?";
            DELETE = "Видалити";
            VIEW_DELETED = "Переглянути видалені";
            GHOST_MODE_ENABLED = "Режим привида увімкнено";
            GHOST_MODE_DISABLED = "Режим привида вимкнено";
            GHOST_IN_DRAWER = "Кнопка привида в бічному меню";
            SPY = "Шпигун";
            CUSTOMIZATION = "Кастомізація";
            GHOST_MODE_ENABLE = "Увімкнути привида";
            GHOST_MODE_DISABLE = "Вимкнути привида";
            ADD_SETTINGS_TO_DRAWER = "Налаштування в бічному меню";
            LOCAL_PREMIUM = "Локальний преміум";
            CANT_USE_WITH_PREMIUM = "Не можна використовувати з преміум акаунтом";
            RESTART_APP = "Перезапустити додаток";
            RESTART_APP_ABOUT = "Це вирішує 99% всіх проблем";
            SEND_SILENCE = "Надсилати без звуку";
            ONLY_WITH_GHOST = "Тільки з привидом";
            DELETED_MESSAGES_TITLE = "Видалені повідомлення";
            UNLOAD_REEXTERA = "Вивантажити хуки re:extera";
            UNLOAD_SUCCESSFULL = "Вивантажено успішно";
            WE_BROKE_SOMETHING = "Ми щось зламали...";
            BROKE_HOOKS_DESCRIPTION = "Додаток не зміг ініціалізувати необхідні хуки. re:extera не працюватиме\n\nЗакрити додаток чи продовжити?";
            CLOSE_APPLICATION = "Закрити додаток";
            CONTINUE_ANYWAY = "Все одно продовжити";
            READ_ON_INTERACT = "Читати при діях";
            SHADOWBAN = "Тіньовий бан";
            ADD_TO_SHADOWBAN = "Додати до тіньового бану";
            REMOVE_FROM_SHADOWBAN = "Прибрати з тіньового бану";
            EDIT_SHADOWBAN = "Редагувати";
            NO_SHADOWBANNED = "Список порожній";
            HIDE_DIALOG = "Приховати діалог";
            HIDE_IN_GROUPS = "Приховати в групах";
            SHADOWBAN_ABOUT = "Тіньовий бан дозволяє приховати діалог користувача та/або його повідомлення в групах";
            FILTERED_MESSAGE = "Відфільтровано";
            return;
        }
        HIDE_READING_MESSAGE = "Don't read messages";
        HIDE_TYPING_STATUS = "Don't send \"typing\"";
        HIDE_ONLINE_STATUS = "Don't send \"online\"";
        NO_READ_STORIES = "Don't read stories";
        GENERAL = "General";
        THANKS = "Thanks to @bleizix";
        ENABLE_ALPHA = "Transparent deleted messages";
        ALPHA_WARNING = "This function eats a lot of cpu";
        RE_EXTERA_SETTINGS = "re:extera Settings";
        SAVE_DELETED_MESSAGES = "Save deleted messages";
        SAVE_BOT_CHATS = "Save in bot chats";
        SAVE_READ_DATE = "Save read date";
        SAVE_LAST_ONLINE = "Save last online";
        SAVE_ATTACHMENTS = "Save attachments";
        SAVE_ATTACHMENTS_SIZE = "Maximum folder size";
        SAVE_ATTACHMENTS_DESC = "Deleted media will be saved to Downloads/ReExtera/ReExteraAttachments. Oldest files will be removed if the limit is exceeded.";
        EXPORT_DB = "Export DB";
        IMPORT_DB = "Import DB";
        IMPORT_SUCCESSFUL = "Imported successfully! Restarting...";
        IMPORT_FAILED = "Import failed: ";
        EXPORT_SUCCESSFUL = "Exported to Downloads!";
        EXPORT_FAILED = "Export failed: ";
        DB_NOT_FOUND = "Database not found";
        READ_AT = "Read at %s";
        MESSAGE_HISTORY = "History";
        MESSAGE_HISTORY_TOGGLE = "Save message history";
        MESSAGE_HISTORY_TITLE = "Message history";
        REMOVE_FLAG_SECURE = "Ignore FLAG_SECURE";
        USE_SCHEDULE = "Use schedule to send";
        CLEAR_DB = "Clear DB";
        YES = "Yes";
        NO = "No";
        CUSTOM_PREFIX = "Deleted message mark";
        LEAVE_BLANK_FOR_RECYCLE = "Leave blank for 🗑 icon️";
        GHOST_MODE = "Ghost mode";
        UNLIMITED = "Unlimited";
        DELETED_AND_EDITED_MESSAGES = "Edited and deleted messages";
        OTHER = "Other";
        NO_FORWARD = "re:forward";
        NO_FORWARD_ABOUT = "re:forward allows you to pseudo-forward messages from chats where this is forbidden";
        RED_DELETED_MARK = "Red deleted mark";
        EXCLUSIONS = "Exclusions";
        EXCEPTION_READING_TEXT = "Exclusion reading";
        EXCEPTION_TYPING_TEXT = "Typing Exception";
        GHOST_EXCLUDE_GROUPS = "Do not apply to groups";
        GHOST_EXCLUDE_CHANNELS = "Do not apply to channels";
        GHOST_EXCLUDE_PMS = "Do not apply to PMs";
        BASED_ON_GLOBAL = "Based on Global";
        ALWAYS = "Always";
        NEVER = "Never";
        READ = "read";
        TYPE = "type";
        NOT = "";
        READ_TO = "Read: ";
        TYPE_TO = "Type: ";
        CLEARING_NOW = "Clearing...";
        CLEAR_DELETED = "Clear deleted";
        FORWARDED_TO_SAVED_MESSAGES = "Forwarded to saved messages";
        INFINITY_STARS = "Infinity stars";
        FORWARDED = "Forwarding...";
        CANCEL = "Cancel";
        SAVE_ONE_TIME_MESSAGES = "Save self-destruct messages";
        DISABLE_BLUR = "Disable blur";
        HOLD_FOR_ADDITIONAL_SETTINGS = "Hold for additional settings";
        ADDITIONAL_SETTINGS = "Additional settings";
        IMMEDIATE_OFFLINE = "Immediate offline";
        SAVE_OWN_MESSAGES = "Save own messages";
        SAVE_SELF_DELETED_MESSAGES = "Save manually deleted messages";
        ABOUT_SAVE_SELF_DELETED_MESSAGES = "Saves messages you manually deleted through \"Delete\" menu";
        OFFLINE = "offline?";
        USE_COLLAPSED_BLOCKQUOTE = "Use collapsed quote";
        USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION = "Use collapsed quote for reply to deleted messages";
        OPEN_CHAT = "Open chat";
        EDIT_TYPING = "Edit typing exclusion";
        EDIT_READ = "Edit read exclusion";
        EDIT_FILTER = "Edit filter exclusion";
        DELETE_FROM_EXCLUSIONS = "Delete from exclusions";
        UNKNOWN_DIALOG = "Unknown dialog";
        NO_EXLCUSIONS = "No exclusions";
        DISABLE_ADS = "Disable ads";
        HIDE_PINNED_MESSAGES = "Hide pinned messages";
        DISABLE_CHAT_SWIPE_BACK = "Disable chat swipe back";
        DISABLE_PROFILE_SWIPE = "Disable profile swipe";
        SAVE_PROTECTED_STORIES = "Save protected stories";
        HIDE_TL_ERROR = "Hide TL error";
        SHOW_MESSAGE_ID = "Show message ID";
        SHOW_ID_IN_MENU = "Show ID in profile menu";
        ID_COPIED = "ID copied to clipboard";
        DELETED_MESSAGE = "Deleted Message";
        MESSAGE_DETAILS = "Message Details";
        SAVE_TO_SAVED_MESSAGES = "Save to Saved Messages";
        VIEW_ONCE = "Save view-once media";
        VIEW_ONCE_ABOUT = "View-once photos and videos won't self-destruct after viewing.";
        MESSAGE_QUICK_BUTTONS = "Message quick buttons (edit / save)";
        DISABLE_COLORED_REPLIES = "Disable colored replies";
        WORK_IN_BACKGROUND = "Work in background";
        FILTERS = "Filters";
        ADD = "Add";
        SAVE = "Save";
        EDIT_REGEX_PATTERN = "Filter";
        EDIT_REGEX_FILTER = "Edit filter";
        ADD_REGEX_FILTER = "Add filter";
        PATTERN_ERROR = "Pattern error";
        DELETE_FILTER = "Delete filter";
        DELETE_FILTER_ABOUT = "Delete filter?";
        ENABLE_FILTERS = "Enable filters";
        FILTERS_ABOUT = "Filters allow you to hide messages that match the regex pattern. Use regex101.com to create filters";
        COPY_FILTER = "Copy filter";
        COPIED = "Copied";
        READ_MESSAGE = "Read";
        FINALLY_REMOVE_ALL_DELETED_MESSAGES = "Finally remove all deleted messages?";
        DELETE = "Delete";
        VIEW_DELETED = "View deleted";
        GHOST_MODE_ENABLED = "Ghost mode enabled";
        GHOST_MODE_DISABLED = "Ghost mode disabled";
        GHOST_IN_DRAWER = "Ghost button in side menu";
        SPY = "Spy";
        CUSTOMIZATION = "Customization";
        GHOST_MODE_ENABLE = "Enable ghost";
        GHOST_MODE_DISABLE = "Disable ghost";
        ADD_SETTINGS_TO_DRAWER = "Settings in side menu";
        LOCAL_PREMIUM = "Local Premium";
        CANT_USE_WITH_PREMIUM = "Can't use with premium account";
        RESTART_APP = "Restart app";
        RESTART_APP_ABOUT = "This solves 99% of all problems";
        SEND_SILENCE = "Send silence";
        ONLY_WITH_GHOST = "Only with ghost";
        DELETED_MESSAGES_TITLE = "Deleted messages";
        UNLOAD_REEXTERA = "Unload re:extera hooks";
        UNLOAD_SUCCESSFULL = "Unloaded successfully";
        WE_BROKE_SOMETHING = "We broke something...";
        BROKE_HOOKS_DESCRIPTION = "The application failed to initialize necessary hooks. re:extera will not work.\n\nWould you like to close the app or continue anyway?";
        CLOSE_APPLICATION = "Close Application";
        CONTINUE_ANYWAY = "Continue anyway";
        READ_ON_INTERACT = "Read on interact";
        SHADOWBAN = "Shadowban";
        ADD_TO_SHADOWBAN = "Add to shadowban";
        REMOVE_FROM_SHADOWBAN = "Remove from shadowban";
        EDIT_SHADOWBAN = "Edit";
        NO_SHADOWBANNED = "List is empty";
        HIDE_DIALOG = "Hide dialog";
        HIDE_IN_GROUPS = "Hide in groups";
        SHADOWBAN_ABOUT = "Shadowban allows you to hide user's dialog and/or their messages in groups";
        FILTERED_MESSAGE = "Filtered";
    }
}
