package ni.shikatu.re_extera.localization;

import org.telegram.messenger.LocaleController;

public class Localization {
    public static String ABOUT_SAVE_SELF_DELETED_MESSAGES;
    public static String ADD;
    public static String ADDITIONAL_SETTINGS;
    public static String ADD_REGEX_FILTER;
    public static String ADD_SETTINGS_TO_DRAWER;
    public static String ALPHA_WARNING;
    public static String ALWAYS;
    public static String BASED_ON_GLOBAL;
    public static String CANCEL;
    public static String CANT_USE_WITH_PREMIUM;
    public static String CLEARING_NOW;
    public static String CLEAR_DB;
    public static String CLEAR_DELETED;
    public static String COPIED;
    public static String COPY_FILTER;
    public static String CUSTOM_PREFIX;
    public static String DELETE;
    public static String DELETED_AND_EDITED_MESSAGES;
    public static String DELETE_FILTER;
    public static String DELETE_FILTER_ABOUT;
    public static String DELETE_FROM_EXCLUSIONS;
    public static String DISABLE_ADS;
    public static String DISABLE_BLUR;
    public static String EDIT_READ;
    public static String EDIT_REGEX_FILTER;
    public static String EDIT_REGEX_PATTERN;
    public static String EDIT_TYPING;
    public static String ENABLE_ALPHA;
    public static String ENABLE_FILTERS;
    public static String EXCEPTION_READING_TEXT;
    public static String EXCEPTION_TYPING_TEXT;
    public static String EXCLUSIONS;
    public static String FILTERS;
    public static String FILTERS_ABOUT;
    public static String FINALLY_REMOVE_ALL_DELETED_MESSAGES;
    public static String FORWARDED;
    public static String FORWARDED_TO_SAVED_MESSAGES;
    public static String GENERAL;
    public static String GHOST_IN_DRAWER;
    public static String GHOST_MODE;
    public static String GHOST_MODE_DISABLE;
    public static String GHOST_MODE_DISABLED;
    public static String GHOST_MODE_ENABLE;
    public static String GHOST_MODE_ENABLED;
    public static String HIDE_ONLINE_STATUS;
    public static String HIDE_READING_MESSAGE;
    public static String HIDE_TYPING_STATUS;
    public static String HOLD_FOR_ADDITIONAL_SETTINGS;
    public static String IMMEDIATE_OFFLINE;
    public static String INFINITY_STARS;
    public static String LEAVE_BLANK_FOR_RECYCLE;
    public static String LOCAL_PREMIUM;
    public static String MESSAGE_HISTORY;
    public static String MESSAGE_HISTORY_TITLE;
    public static String MESSAGE_HISTORY_TOGGLE;
    public static String NEVER;
    public static String NO;
    public static String NOT;
    public static String NO_EXLCUSIONS;
    public static String NO_FORWARD;
    public static String NO_FORWARD_ABOUT;
    public static String NO_READ_STORIES;
    public static String OFFLINE;
    public static String ONLY_WITH_GHOST;
    public static String OPEN_CHAT;
    public static String OTHER;
    public static String PATTERN_ERROR;
    public static String READ;
    public static String READ_MESSAGE;
    public static String READ_TO;
    public static String RED_DELETED_MARK;
    public static String REMOVE_FLAG_SECURE;
    public static String RESTART_APP;
    public static String RESTART_APP_ABOUT;
    public static String RE_EXTERA_SETTINGS;
    public static String SAVE;
    public static String SAVE_DELETED_MESSAGES;
    public static String SAVE_ONE_TIME_MESSAGES;
    public static String SAVE_OWN_MESSAGES;
    public static String SAVE_SELF_DELETED_MESSAGES;
    public static String SEND_SILENCE;
    public static String SPY;
    public static String THANKS;
    public static String TYPE;
    public static String TYPE_TO;
    public static String UNKNOWN_DIALOG;
    public static String USE_COLLAPSED_BLOCKQUOTE;
    public static String USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION;
    public static String USE_SCHEDULE;
    public static String VIEW_DELETED;
    public static String YES;

    public static void updateStrings() {
        String currentLang = LocaleController.getInstance().getCurrentLocale().getLanguage();
        if ("ru".equals(currentLang)) {
            HIDE_READING_MESSAGE = "Не читать сообщения";
            HIDE_TYPING_STATUS = "Не отправлять \"печатает\"";
            HIDE_ONLINE_STATUS = "Не отправлять \"онлайн\"";
            NO_READ_STORIES = "Не читать истории";
            ENABLE_ALPHA = "Полупрозрачные удаленки";
            ALPHA_WARNING = "Эта функция кушает очень много";
            GENERAL = "Общие";
            THANKS = "Спасибо @bleizix";
            RE_EXTERA_SETTINGS = "Настройки re:extera";
            SAVE_DELETED_MESSAGES = "Сохранять удаленные сообщения";
            MESSAGE_HISTORY = "История";
            MESSAGE_HISTORY_TOGGLE = "Сохранить историю правок";
            MESSAGE_HISTORY_TITLE = "История правок";
            REMOVE_FLAG_SECURE = "Игнорировать FLAG_SECURE";
            USE_SCHEDULE = "Использовать отложку";
            CLEAR_DB = "Очистить БД";
            YES = "Да";
            NO = "Нет";
            CUSTOM_PREFIX = "Метка удаленок";
            LEAVE_BLANK_FOR_RECYCLE = "Оставьте пустым для иконки 🗑️";
            GHOST_MODE = "Режим призрака";
            DELETED_AND_EDITED_MESSAGES = "Измененные и удаленные сообщения";
            OTHER = "Другое";
            NO_FORWARD = "re:forward";
            NO_FORWARD_ABOUT = "re:forward позволяет псевдопересылать сообщения из чатов, где это запрещено";
            RED_DELETED_MARK = "Красная метка удаленок";
            EXCLUSIONS = "Исключения";
            EXCEPTION_READING_TEXT = "Исключение нечиталки";
            EXCEPTION_TYPING_TEXT = "Исключение неписалки";
            BASED_ON_GLOBAL = "В зависимости от глобальных";
            ALWAYS = "Всегда";
            NEVER = "Никогда";
            NOT = " не ";
            READ = "читать";
            TYPE = "писать";
            READ_TO = "Читать: ";
            TYPE_TO = "Печатать: ";
            DISABLE_ADS = "Отключить рекламу";
            CLEARING_NOW = "Очистка...";
            CLEAR_DELETED = "Очистить удаленные";
            FORWARDED_TO_SAVED_MESSAGES = "Переслано в избранное";
            INFINITY_STARS = "Бесконечное количество звезд";
            FORWARDED = "Идет пересылка...";
            CANCEL = "Отмена";
            SAVE_ONE_TIME_MESSAGES = "Сохранять самоуничтожающиеся сообщения";
            DISABLE_BLUR = "Отключить размытие";
            HOLD_FOR_ADDITIONAL_SETTINGS = "Удерживайте для дополнительных настроек";
            ADDITIONAL_SETTINGS = "Дополнительные настройки";
            IMMEDIATE_OFFLINE = "Немедленный оффлайн";
            SAVE_OWN_MESSAGES = "Сохранять свои сообщения";
            SAVE_SELF_DELETED_MESSAGES = "Сохранять сообщения удаленные вручную";
            ABOUT_SAVE_SELF_DELETED_MESSAGES = "Сохраняет сообщения, которые вы самостоятельно удалили через меню \"Удалить\"";
            OFFLINE = "оффлайн?";
            USE_COLLAPSED_BLOCKQUOTE = "Использовать свернутую цитату";
            USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION = "Использовать свернутую цитату для ответа на удаленные сообщения";
            OPEN_CHAT = "Открыть чат";
            EDIT_TYPING = "Изменить исключение неписалки";
            EDIT_READ = "Изменить исключение нечиталки";
            DELETE_FROM_EXCLUSIONS = "Удалить из исключений";
            UNKNOWN_DIALOG = "Неизвестный диалог";
            NO_EXLCUSIONS = "Нет исключений";
            FILTERS = "Фильтры";
            ADD = "Добавить";
            SAVE = "Сохранить";
            EDIT_REGEX_PATTERN = "Фильтр";
            EDIT_REGEX_FILTER = "Изменить фильтр";
            ADD_REGEX_FILTER = "Добавить фильтр";
            PATTERN_ERROR = "Ошибка шаблона";
            DELETE_FILTER = "Удалить фильтр";
            DELETE_FILTER_ABOUT = "Удалить фильтр?";
            ENABLE_FILTERS = "Включить фильтры";
            FILTERS_ABOUT = "Фильтры позволяют скрывать сообщения, подходящие под regex паттерн.\nИспользуйте regex101.com для составления фильтров.";
            COPY_FILTER = "Копировать фильтр";
            COPIED = "Скопировано";
            READ_MESSAGE = "Прочитать";
            FINALLY_REMOVE_ALL_DELETED_MESSAGES = "Окончательно далить все удаленные сообщения?";
            DELETE = "Удалить";
            VIEW_DELETED = "Посмотреть удаленки";
            GHOST_MODE_ENABLED = "Режим призрака включен";
            GHOST_MODE_DISABLED = "Режим призрака выключен";
            GHOST_IN_DRAWER = "Кнопка призрака в боковом меню";
            SPY = "Шпион";
            GHOST_MODE_ENABLE = "Включить призрака";
            GHOST_MODE_DISABLE = "Выключить призрака";
            ADD_SETTINGS_TO_DRAWER = "Настройки в боковом меню";
            LOCAL_PREMIUM = "Локальный премиум";
            CANT_USE_WITH_PREMIUM = "Нельзя использовать с премиум аккаунтом";
            RESTART_APP = "Перезапустить приложение";
            RESTART_APP_ABOUT = "Это решает 99% всех проблем";
            SEND_SILENCE = "Отправлять без звука";
            ONLY_WITH_GHOST = "Только с призраком";
            return;
        }
        HIDE_READING_MESSAGE = "Don't read messages";
        HIDE_TYPING_STATUS = "Don't send \"typing\"";
        HIDE_ONLINE_STATUS = "Don't send \"online\"";
        NO_READ_STORIES = "Don't read stories";
        GENERAL = "General";
        THANKS = "Thanks to @bleizix";
        ENABLE_ALPHA = "Half opacity for deleted messages";
        ALPHA_WARNING = "This function eats a lot of cpu";
        RE_EXTERA_SETTINGS = "re:extera Settings";
        SAVE_DELETED_MESSAGES = "Save deleted messages";
        MESSAGE_HISTORY = "History";
        MESSAGE_HISTORY_TOGGLE = "Save message history";
        MESSAGE_HISTORY_TITLE = "Message history";
        REMOVE_FLAG_SECURE = "Ignore FLAG_SECURE";
        USE_SCHEDULE = "Use schedule to send";
        CLEAR_DB = "Clear DB";
        YES = "Yes";
        NO = "No";
        CUSTOM_PREFIX = "Deleted message mark";
        LEAVE_BLANK_FOR_RECYCLE = "Leave blank for 🗑 icon️";
        GHOST_MODE = "Ghost mode";
        DELETED_AND_EDITED_MESSAGES = "Edited and deleted messages";
        OTHER = "Other";
        NO_FORWARD = "re:forward";
        NO_FORWARD_ABOUT = "re:forward allows you to pseudo-forward messages from chats where this is forbidden";
        RED_DELETED_MARK = "Red deleted mark";
        EXCLUSIONS = "Exclusions";
        EXCEPTION_READING_TEXT = "Exclusion reading";
        EXCEPTION_TYPING_TEXT = "Exclusion typing";
        BASED_ON_GLOBAL = "Based on global";
        ALWAYS = "Always";
        NEVER = "Never";
        READ = "read";
        TYPE = "type";
        NOT = "";
        READ_TO = "Read: ";
        TYPE_TO = "Type: ";
        CLEARING_NOW = "Clearing...";
        CLEAR_DELETED = "Clear deleted";
        FORWARDED_TO_SAVED_MESSAGES = "Forwarded to saved messages";
        INFINITY_STARS = "Infinity stars";
        FORWARDED = "Forwarding...";
        CANCEL = "Cancel";
        SAVE_ONE_TIME_MESSAGES = "Save self-destruct messages";
        DISABLE_BLUR = "Disable blur";
        HOLD_FOR_ADDITIONAL_SETTINGS = "Hold for additional settings";
        ADDITIONAL_SETTINGS = "Additional settings";
        IMMEDIATE_OFFLINE = "Immediate offline";
        SAVE_OWN_MESSAGES = "Save own messages";
        SAVE_SELF_DELETED_MESSAGES = "Save manually deleted messages";
        ABOUT_SAVE_SELF_DELETED_MESSAGES = "Saves messages you manually deleted through \"Delete\" menu";
        OFFLINE = "offline?";
        USE_COLLAPSED_BLOCKQUOTE = "Use collapsed quote";
        USE_COLLAPSED_BLOCKQUOTE_DESCRIPTION = "Use collapsed quote for reply to deleted messages";
        OPEN_CHAT = "Open chat";
        EDIT_TYPING = "Edit typing exclusion";
        EDIT_READ = "Edit read exclusion";
        DELETE_FROM_EXCLUSIONS = "Delete from exclusions";
        UNKNOWN_DIALOG = "Unknown dialog";
        NO_EXLCUSIONS = "No exclusions";
        DISABLE_ADS = "Disable ads";
        FILTERS = "Filters";
        ADD = "Add";
        SAVE = "Save";
        EDIT_REGEX_PATTERN = "Filter";
        EDIT_REGEX_FILTER = "Edit filter";
        ADD_REGEX_FILTER = "Add filter";
        PATTERN_ERROR = "Pattern error";
        DELETE_FILTER = "Delete filter";
        DELETE_FILTER_ABOUT = "Delete filter?";
        ENABLE_FILTERS = "Enable filters";
        FILTERS_ABOUT = "Filters allow you to hide messages that match the regex pattern. Use regex101.com to create filters";
        COPY_FILTER = "Copy filter";
        COPIED = "Copied";
        READ_MESSAGE = "Read";
        FINALLY_REMOVE_ALL_DELETED_MESSAGES = "Finally remove all deleted messages?";
        DELETE = "Delete";
        VIEW_DELETED = "View deleted";
        GHOST_MODE_ENABLED = "Ghost mode enabled";
        GHOST_MODE_DISABLED = "Ghost mode disabled";
        GHOST_IN_DRAWER = "Ghost button in side menu";
        SPY = "Spy";
        GHOST_MODE_ENABLE = "Enable ghost";
        GHOST_MODE_DISABLE = "Disable ghost";
        ADD_SETTINGS_TO_DRAWER = "Settings in side menu";
        LOCAL_PREMIUM = "Local Premium";
        CANT_USE_WITH_PREMIUM = "Can't use with premium account";
        RESTART_APP = "Restart app";
        RESTART_APP_ABOUT = "This solves 99% of all problems";
        SEND_SILENCE = "Send silence";
        ONLY_WITH_GHOST = "Only with ghost";
    }
}
