__id__ = "re_extera_loader"
__name__ = "aartzz's re:extera"
__description__ = "Actively maintained FOSS fork. Enable ghost mode, save deleted messages and more!"
__author__ = "@shiawasez | @shikaatuxplugins \noriginal author: @bleizixPlugins\nFOSS recovery by @fossSquad & @migor1103"
__version__ = "2.9.0"
__icon__ = "myadestes_1_amashiro_natsuki_plus_nacho_neko/30"
__min_version__ = "12.8.1"